### ISSUE TITLE
bug: didn't load more messages when messagesLoaded once set to true

### ISSUE THREAD

**Issue by Clansty** [antoine92190/vue-advanced-chat#123]
```js
	fetchMessage(data) {
		console.log(data)
		if (data.options) {
			this.messagesLoaded = false
			this.messages = []
			data.room.unreadCount = 0
			this.selectedRoom = data.room
			db.set("rooms", this.rooms).write()
			const muted = (data.room.roomId < 0 && this.muteAllGroups && !data.room.unmute) ||
				(data.room.roomId < 0 && !this.muteAllGroups && data.room.mute) ||
				(data.room.roomId > 0 && data.room.mute)
			this.menuActions.find(e => e.name == "mute").title = muted ? "Unmute Chat" : "Mute Chat"
			this.menuActions.find(e => e.name == "pin").title = data.room.index ? "Unpin Chat" : "Pin Chat"
		}
		const msgs2add = db.get("messages." + data.room.roomId)
			.dropRightWhile(e => this.messages.includes(e))
			.takeRight(10).value()
		if (msgs2add.length)
			this.messages = [...msgs2add, ...this.messages]
		else
			this.messagesLoaded = true
	},
```
Once I scrolled to the very top of a conversation, then switch to another room, then switch back. It just loaded the last 10 messages and doesn't load more messages any more, Even I switch to other room which have more than 10 messages

**Comment by antoine92190** [comment]
Please read the last bullet point (UI loading pattern): https://github.com/antoine92190/vue-advanced-chat#important-notes
Let me know if it helps

**Comment by Clansty** [comment]
ok

**Comment by Clansty** [comment]
but it doesn't work

https://user-images.githubusercontent.com/18461360/106374232-01cac700-63bc-11eb-9047-068c8022cda3.mp4

**Comment by antoine92190** [comment]
Do you have any console errors?
If not, can you give me access to your repo so I can reproduce on my end?

**Comment by Clansty** [comment]
I didn't set `room.users[*].username`, does it matter?

**Comment by Clansty** [comment]
Invitation sent

copy the two files from `demo-config` to `%appdata%\Electron` or equivalent Electron data dir, than `yarn install` and `yarn dev:ui`. Then you can inspect the UI

**Comment by antoine92190** [comment]
Thanks. I'm not sure where I should put those config file as I'm not familiar with Electron.
Could you give me more detailed steps after cloning the electron-qq repo?

**Comment by Clansty** [comment]
What OS do you use? If you are using windows, it should be `C:\Users\USERNAME\AppData\Roaming\Electron`. For Linux it's in `~/.config`. MacOS is `~/Library/Application Support`

**Comment by antoine92190** [comment]
I'm on MacOS, so what should I do in the `~/Library/Application Support` folder? Should I install anything?

**Comment by antoine92190** [comment]
Ok I found out, and can reproduce the issue. Where can I see the debug console, for example if I want to console log something where will it show?

**Comment by antoine92190** [comment]
I see errors in the console: `"Rooms object is not valid! Must contain roomId[String, Number], roomName[String] and users[Array]"`

Your `rooms` data is missing `users`. Should be like: https://github.com/antoine92190/vue-advanced-chat#rooms-prop

**Comment by antoine92190** [comment]
Each user should have at least an `_id` and `username`

**Comment by Clansty** [comment]
I'll try it tomorrow

**Comment by Clansty** [comment]
I added the `users` array in the config file and there's no console errors, but the issue is still there

And I found the `InfiniteLoading` component's status is `2`
![image](https://user-images.githubusercontent.com/18461360/106415228-8d5e5980-6489-11eb-9b02-0e23c534bdba.png)

The new data store files are uploaded to git repo, and you can try it by yourself.

Thank you very much!

**Comment by antoine92190** [comment]
Try to do:
```
setTimeout(() => {
	if (msgs2add.length)
		this.messages = [...msgs2add, ...this.messages]
	else
			this.messagesLoaded = true
	}, 0)
},
```
This partly fixes the issue, but it's still not working properly.
I will try other things later but maybe you can start with this and find some ideas from there

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/commit/51dc892bf82bee7afa3feb130095c854307afe30
Could you install the latest version of the chat component using `npm i github:antoine92190/vue-advanced-chat` and let me know if it works?

**Comment by Clansty** [comment]
Using the latest version together with 
```js
setTimeout(() => {
  if (msgs2add.length)
    this.messages = [...msgs2add, ...this.messages]
  else
    this.messagesLoaded = true
}, 0)
```
works both in development and production(with much more messages) environment, thank you very much!!

But if I don't put `this.messages = [...msgs2add, ...this.messages]` inside `setTimeout` it still won't work, and in this case when I open a chat room the view will scroll to the top of the loaded messages but not the bottom. All of these two will fix if I include `this.messages = [...msgs2add, ...this.messages]` in `setTimeout`

**Comment by antoine92190** [comment]
Yes the timeout is necessary to make the behaviour work properly.
